// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$1 from "./loaders/availableIcons.ts";
import * as $$$0 from "./loaders/Bag.tsx";
import * as $$$2 from "./loaders/icons.ts";
import * as $$$3 from "./loaders/minicart.ts";
import * as $$$4 from "./loaders/user.ts";
import * as $$$5 from "./loaders/wishlist.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/BalletSection.tsx";
import * as $$$$$$2 from "./sections/CalendarSection.tsx";
import * as $$$$$$3 from "./sections/Calender.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$6 from "./sections/Component.tsx";
import * as $$$$$$7 from "./sections/Content/Faq.tsx";
import * as $$$$$$8 from "./sections/Content/Hero.tsx";
import * as $$$$$$9 from "./sections/Content/Intro.tsx";
import * as $$$$$$10 from "./sections/Content/Logos.tsx";
import * as $$$$$$11 from "./sections/Content/Title.tsx";
import * as $$$$$$13 from "./sections/Footer/Footer.tsx";
import * as $$$$$$12 from "./sections/FooterBallet.tsx";
import * as $$$$$$14 from "./sections/GoogleMaps.tsx";
import * as $$$$$$15 from "./sections/Header/Header.tsx";
import * as $$$$$$16 from "./sections/Images/Banner.tsx";
import * as $$$$$$17 from "./sections/Images/Carousel.tsx";
import * as $$$$$$18 from "./sections/Images/CarrouselGridBallet.tsx";
import * as $$$$$$19 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$20 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$21 from "./sections/Institutional/AccordionsContent.tsx";
import * as $$$$$$22 from "./sections/Institutional/AsideMenu.tsx";
import * as $$$$$$23 from "./sections/Institutional/CardsContent.tsx";
import * as $$$$$$24 from "./sections/Institutional/ContactForm.tsx";
import * as $$$$$$25 from "./sections/Institutional/HelpHomePage.tsx";
import * as $$$$$$26 from "./sections/Institutional/HelpPage.tsx";
import * as $$$$$$27 from "./sections/Institutional/HtmlContent.tsx";
import * as $$$$$$28 from "./sections/Institutional/InstitutionalPage.tsx";
import * as $$$$$$29 from "./sections/Institutional/LegalsPage.tsx";
import * as $$$$$$30 from "./sections/Institutional/PageContent.tsx";
import * as $$$$$$31 from "./sections/Institutional/PolicyPage.tsx";
import * as $$$$$$32 from "./sections/Institutional/ResellerForm.tsx";
import * as $$$$$$33 from "./sections/Institutional/TextContent.tsx";
import * as $$$$$$34 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$35 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$36 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$37 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$38 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$39 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$40 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$41 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$42 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$43 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$44 from "./sections/Session.tsx";
import * as $$$$$$45 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$46 from "./sections/TextWithBanner.tsx";
import * as $$$$$$47 from "./sections/Theme/Theme.tsx";
import * as $$$$$$48 from "./sections/Video.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$1,
    "site/loaders/Bag.tsx": $$$0,
    "site/loaders/icons.ts": $$$2,
    "site/loaders/minicart.ts": $$$3,
    "site/loaders/user.ts": $$$4,
    "site/loaders/wishlist.ts": $$$5,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/BalletSection.tsx": $$$$$$1,
    "site/sections/CalendarSection.tsx": $$$$$$2,
    "site/sections/Calender.tsx": $$$$$$3,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$4,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$5,
    "site/sections/Component.tsx": $$$$$$6,
    "site/sections/Content/Faq.tsx": $$$$$$7,
    "site/sections/Content/Hero.tsx": $$$$$$8,
    "site/sections/Content/Intro.tsx": $$$$$$9,
    "site/sections/Content/Logos.tsx": $$$$$$10,
    "site/sections/Content/Title.tsx": $$$$$$11,
    "site/sections/Footer/Footer.tsx": $$$$$$13,
    "site/sections/FooterBallet.tsx": $$$$$$12,
    "site/sections/GoogleMaps.tsx": $$$$$$14,
    "site/sections/Header/Header.tsx": $$$$$$15,
    "site/sections/Images/Banner.tsx": $$$$$$16,
    "site/sections/Images/Carousel.tsx": $$$$$$17,
    "site/sections/Images/CarrouselGridBallet.tsx": $$$$$$18,
    "site/sections/Images/ImageGallery.tsx": $$$$$$19,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$20,
    "site/sections/Institutional/AccordionsContent.tsx": $$$$$$21,
    "site/sections/Institutional/AsideMenu.tsx": $$$$$$22,
    "site/sections/Institutional/CardsContent.tsx": $$$$$$23,
    "site/sections/Institutional/ContactForm.tsx": $$$$$$24,
    "site/sections/Institutional/HelpHomePage.tsx": $$$$$$25,
    "site/sections/Institutional/HelpPage.tsx": $$$$$$26,
    "site/sections/Institutional/HtmlContent.tsx": $$$$$$27,
    "site/sections/Institutional/InstitutionalPage.tsx": $$$$$$28,
    "site/sections/Institutional/LegalsPage.tsx": $$$$$$29,
    "site/sections/Institutional/PageContent.tsx": $$$$$$30,
    "site/sections/Institutional/PolicyPage.tsx": $$$$$$31,
    "site/sections/Institutional/ResellerForm.tsx": $$$$$$32,
    "site/sections/Institutional/TextContent.tsx": $$$$$$33,
    "site/sections/Links/LinkTree.tsx": $$$$$$34,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$35,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$36,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$37,
    "site/sections/Product/ProductDetails.tsx": $$$$$$38,
    "site/sections/Product/ProductShelf.tsx": $$$$$$39,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$40,
    "site/sections/Product/SearchResult.tsx": $$$$$$41,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$42,
    "site/sections/Product/Wishlist.tsx": $$$$$$43,
    "site/sections/Session.tsx": $$$$$$44,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$45,
    "site/sections/TextWithBanner.tsx": $$$$$$46,
    "site/sections/Theme/Theme.tsx": $$$$$$47,
    "site/sections/Video.tsx": $$$$$$48,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/wishlist/submit.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
